<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AddCity.aspx.cs" Inherits="_1_Authentication.AddCity" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <table class="style1" width="100%">
                <tr>
                    <td class="style3">
                        <h2>Add City</h2>
                    </td>
                    <td>
                        <asp:ScriptManager ID="ScriptManager1" runat="server">
                        </asp:ScriptManager>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="style4">City Name</td>
                    <td>
                        <asp:TextBox ID="txtCityName" runat="server" ValidationGroup="A"></asp:TextBox>
                    </td>
                    <td>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server"
                            ControlToValidate="txtCityName" ErrorMessage="This information is required" ValidationGroup="A"></asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <td class="style4">&nbsp;</td>
                    <td>
                        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click"
                            Text="Add City" ValidationGroup="A" />
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="style3">&nbsp;</td>
                    <td>
                        <asp:Label ID="Label1" runat="server"></asp:Label>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="style3">&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="style3" colspan="2">
                        <h2>Already Added Cities</h2>
                    </td>
                    <td class="style3">&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <asp:GridView ID="GridView1" runat="server"
                            OnRowDeleting="OnRowDeleting" 
                            OnRowEditing="GridView1_RowEditing" 
                            OnRowCancelingEdit="GridView1_RowCancelingEdit"
                            OnRowUpdating="GridView1_RowUpdating"
                            EmptyDataText="No records has been added"
                            AutoGenerateEditButton="true"
                            AutoGenerateDeleteButton="true">
                                <%--<Columns>
                  <asp:TemplateField headertext="City" >
                    <ItemTemplate>
                        <asp:Label ID="lblCountry" runat="server" Text='<%# Eval("Country") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtCity" runat="server" ></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                            </Columns>--%>
                        </asp:GridView>
                    </td>
                </tr>
                <%-- <tr>
            <td class="style3" colspan="2">
                <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
                    AutoGenerateColumns="False" DataKeyNames="CityID" DataSourceID="SqlDataSource1" 
                    Width="100%">
                    <Columns>
                        <asp:BoundField DataField="CityName" HeaderText="CityName" 
                            SortExpression="CityName" />
                        <asp:CommandField HeaderText="Edit/Delete" ShowDeleteButton="True" 
                            ShowEditButton="True" CausesValidation="False">
                        <ControlStyle ForeColor="Black" />
                        </asp:CommandField>
                    </Columns>
                </asp:GridView>
                <br />
                <asp:Label ID="Label2" runat="server"></asp:Label>
                <asp:sqldatasource id="sqldatasource1" runat="server" 
                    conflictdetection="compareallvalues" 
                    connectionstring="<%$ connectionstrings:connectionstring %>" 
                    deletecommand="delete from [addcity] where [cityid] = @original_cityid" 
                    insertcommand="insert into [addcity] ([cityname]) values (@cityname)" 
                    oldvaluesparameterformatstring="original_{0}" 
                    selectcommand="select * from [addcity]" 
                    
                    updatecommand="update [addcity] set [cityname] = @cityname where [cityid] = @original_cityid" 
                    onselected="sqldatasource1_selected">
                    <deleteparameters>
                        <asp:parameter name="original_cityid" type="decimal" />
                        <asp:parameter name="original_cityname" type="string" />
                    </deleteparameters>
                    <insertparameters>
                        <asp:parameter name="cityname" type="string" />
                    </insertparameters>
                    <updateparameters>
                        <asp:parameter name="cityname" type="string" />
                        <asp:parameter name="original_cityid" type="decimal" />
                        <asp:parameter name="original_cityname" type="string" />
                    </updateparameters>
                </asp:sqldatasource>
            </td>
            <td class="style3">
                &nbsp;</td>
        </tr>--%>
            </table>
        </div>
    </form>
</body>
</html>
